#!/bin/bash

# Set background
eval `cat ~/.fehbg`

# Set cursor
xsetroot -cursor_name left_ptr

# Load Resources
xrdb -merge .Xresources

# Setup tray icons
trayer --edge top --align right --SetDockType true --SetPartialStrut true \
--expand true --width 10 --transparent true --alpha 0 --tint 0X000000 --height 17 &

# Set background color
# xsetroot -solid midnightblue

# Start D-Bus session
source /etc/X11/xinit/xinitrc.d/30-bus

# Start GNOME-keyring
eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcsll,secrets,ssh)
export GNOME_KEYRING_CONTROL GNOME_KEYRING_PID GPG_AGENT_INFO SSH_AUTH_SOCK

# Exec apps
xscreensaver -no-splash &

if [ -x /usr/bin/wicd-client ] ; then
	wicd-client &
fi

# Start xmonad
exec xmonad
